# Generated by Django 3.2.2 on 2021-05-30 12:02

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('in_stock', models.IntegerField(default=1)),
                ('featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image1', models.ImageField(upload_to=shop.models.image_dir_path)),
                ('image2', models.ImageField(blank=True, upload_to=shop.models.image_dir_path)),
                ('image3', models.ImageField(blank=True, upload_to=shop.models.image_dir_path)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='shop.subcategory')),
            ],
        ),
    ]
